language: node_js
sudo: true
node_js:
- 5.4.1
before_install:
- openssl aes-256-cbc -K $encrypted_3004ba41f581_key -iv $encrypted_3004ba41f581_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- npm install
script:
- npm run build
- scp -r dist/* root@zhangmengke.cn:/home/wwwroot/vegetable.zhangmengke.cn/
